### ISSUE TITLE
Fails to build with openssl 1.0.2o

### ISSUE THREAD

**Issue by Jigoku** [kouya/snownews#22]
I saw [this](https://github.com/kouya/snownews/issues/4) similar issue, however i'm not sure if it's the same problem. On latest slackware-current with openssl-1.0.2o, it fails to build here:
```
gcc main.o netio.o interface.o xmlparse.o updatecheck.o conversions.o dialog.o ui-support.o categories.o about.o cookies.o setup.o net-support.o digcalc.o filters.o io-internal.o os-support.o zlib_interface.o support.o -o snownews  -lncurses -lcrypto -lxml2 -lz -llzma -lm -ldl 
conversions.o: In function `genItemHash':
conversions.c:(.text+0x1275): undefined reference to `EVP_MD_CTX_new'
conversions.c:(.text+0x12f1): undefined reference to `EVP_MD_CTX_free'
digcalc.o: In function `DigestCalcHA1':
digcalc.c:(.text+0x25): undefined reference to `EVP_MD_CTX_new'
digcalc.c:(.text+0xcb): undefined reference to `EVP_MD_CTX_free'
digcalc.o: In function `DigestCalcResponse':
digcalc.c:(.text+0x1e3): undefined reference to `EVP_MD_CTX_new'
digcalc.c:(.text+0x346): undefined reference to `EVP_MD_CTX_free'
collect2: error: ld returned 1 exit status
make: *** [Makefile:35: snownews] Error 1
```
I saw a mention on stackoverflow relating to this error, where a suggestion was to place `-lssl` before `-lcrypto`, however changing the configure script to do that doesn't change the error output. Any ideas how i can get this to build?

**Comment by msharov** [comment]
After the recently merged  commit 92853900740e230ad4a49fec75fecb182ee86c8b, openssl 1.1 is required, rather than 1.0 as stated in the documentation. Pending pull request #20 will update the README to reflect this change.

**Comment by kouya** [comment]
Yes, code was moved to 1.1, so you'll need that one to build. Both libs can be installed in parallel though. 

Not sure if it would make sense to support both. 1.1 even made it into Debian stable and 1.0.2o hasn't been touched for over a year so it's time to move on.  Closing this one.
