### ISSUE TITLE
Doesn't build against openssl 1.1

### ISSUE THREAD

**Issue by kozross** [kouya/snownews#4]
The error came from the following part of the build process:
```
gcc -Wall -Wno-format-y2k -O2 -DLOCALEPATH="\"/usr/local/share/locale\"" -DOS=\"Linux\" -I/usr/include/libxml2     -c -o conversions.o conversions.c
conversions.c: In function ‘genItemHash’:
conversions.c:621:13: error: storage size of ‘mdctx’ isn’t known
  EVP_MD_CTX mdctx;
             ^~~~~
```

**Comment by kouya** [comment]
What openssl version is installed? It does not build with 1.1 because of some incompatible changes. This is one of them so I suspect it's 1.1.

Probably should get rid of openssl dependency anyway and use a stand-alone md5 function.

**Comment by kozross** [comment]
It is indeed 1.1.

**Comment by kouya** [comment]
Hm, I don't have a quick solution for that. As a quick hack I was opting for a statically linked version to add to the downloads but apparently that ended up in yak shaving, so I quickly abandoned the idea. ;)

Short of using openssl 1.0 there is probably no way atm.

The best way would be to ditch openssl dependency and use a stand-alone MD5 implementation. Added #6 for that.

**Comment by msharov** [comment]
This is fixed by commit 92853900740e230ad4a49fec75fecb182ee86c8b, after which openssl 1.1 is the minimum version required.
